# Generated by Django 4.2.13 on 2024-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
