# Generated by Django 4.2.13 on 2024-06-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_query', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_txt', models.TextField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bot_message',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_query.user')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='User_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_txt', models.CharField(max_length=255)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot_message_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doc_query.bot_message')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_query.chat')),
            ],
            options={
                'db_table': 'user_message',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_query.chat')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
