# Generated by Django 4.2.13 on 2024-06-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_query', '0003_bot_message_chat_user_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='user_message',
            name='bot_message_id',
        ),
        migrations.RemoveField(
            model_name='user_message',
            name='chat_id',
        ),
        migrations.DeleteModel(
            name='Bot_Message',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='User_Message',
        ),
    ]
