# Generated by Django 4.2.13 on 2024-06-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_query', '0004_remove_chat_user_id_remove_file_chat_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
